### ISSUE TITLE
Dev/Handlebars: social media icons except tiktok icon not rendering

### ISSUE THREAD

**Issue by JamesHardin02** [Brandonmckie/My-Voyages-Site#6]
On branch dev/handlebars only issue for rendering site is social media icons other then tik tok icon is failing to render in contact partial

**Comment by Brandonmckie** [comment]
I used a different library that's probably why. 
<script src="https://code.iconify.design/iconify-icon/1.0.3/iconify-icon.min.js"></script>

**Comment by JamesHardin02** [comment]
> I used a different library that's probably why.
> 
> <script src="https://code.iconify.design/iconify-icon/1.0.3/iconify-icon.min.js"></script>

Thanks for letting me know. I switched the icon library to font awesome and used their icons. This solved the issue.
